### ISSUE TITLE
cubox openelec ARMv7 Processor rev 10 (v7l)

### ISSUE THREAD

**Issue by golimer** [miltador/cheapstream#1]
OpenELEC:~/test # sh build.sh

Cleaning up...
rm: can't remove 'build_dir': No such file or directory
rm: can't remove 'dist': No such file or directory
Downloading latest AceStream engine for Android...
Connecting to dl.acestream.org (148.251.41.164:80)
Connecting to dl.acestream.org (148.251.41.164:80)

Unpacking...
[acestream.apk]
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of acestream.apk or
        acestream.apk.zip, and cannot find acestream.apk.ZIP, period.
Extracting resources...
unzip:  cannot find or open acestream_bundle/res/raw/_private_py.zip, acestream_bundle/res/raw/_private_py.zip.zip or acestream_bundle/res/raw/_private_py.zip.ZIP.
unzip:  cannot find or open acestream_bundle/res/raw/_private_res.zip, acestream_bundle/res/raw/_private_res.zip.zip or acestream_bundle/res/raw/_private_res.zip.ZIP.
unzip:  cannot find or open acestream_bundle/res/raw/public_res.zip, acestream_bundle/res/raw/public_res.zip.zip or acestream_bundle/res/raw/public_res.zip.ZIP.
Patching Python...
unzip:  cannot find or open acestream_engine/python/lib/python27.zip, acestream_engine/python/lib/python27.zip.zip or acestream_engine/python/lib/python27.zip.ZIP.
cp: can't create 'python27/android.py': Path does not exist
cp: can't create directory 'python27/dns': No such file or directory
cp: can't create 'python27/socket.py': Path does not exist
cp: can't create 'python27/urllib2.py': Path does not exist
Patching AceStream engine...
cp: can't create 'acestream_engine/': Is a directory
chmod: acestream_engine/python/bin/python: No such file or directory
Bundling Python...
build.sh: cd: line 48: can't cd to python27
mv: can't rename 'python27.zip': No such file or directory
Making distributable...
cp: can't stat 'chroot/*': No such file or directory
cp: can't stat 'platform//*': No such file or directory
cp: can't stat 'scripts/start_acestream.sh': No such file or directory
cp: can't stat 'scripts/acestream-user.conf': No such file or directory
cp: can't stat 'scripts/acestream.sh': No such file or directory
mv: can't rename 'build_dir/acestream_engine/*': No such file or directory

**Comment by miltador** [comment]
@golimer, you need to specify your platform as an argument to `build.sh`, e.g:
`$ sh build.sh arm`

**Comment by miltador** [comment]
I hope this issue is solved.

**Comment by golimer** [comment]
i will try tomorrow, btw did you try on raspberry or cubox ?

**Comment by miltador** [comment]
I have Orange Pi One, which has ARMv7 processor, running Armbian and it's working fine.
